version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: adrian
      MYSQL_PASSWORD: Oceano
      MYSQL_ROOT_PASSWORD: Oceano@
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - drunet

  drupal:
    image: drupal:10-apache
    container_name: drupal_app
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 512M
    # quita el volumen para que arranque con el core de Drupal
    networks:
      - drunet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: drupal_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: adrian
      PMA_PASSWORD: Oceano
    networks:
      - drunet

networks:
  drunet: